// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: advent_service.proto

package storage_service

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdventServiceClient is the client API for AdventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdventServiceClient interface {
	Create(ctx context.Context, in *CreateAdventRequest, opts ...grpc.CallOption) (*Advent, error)
	Get(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*GetAdvent, error)
	GetList(ctx context.Context, in *GetListAdventRequest, opts ...grpc.CallOption) (*GetAdventsListResponse, error)
	Update(ctx context.Context, in *UpdateAdventRequest, opts ...grpc.CallOption) (*Advent, error)
	PatchUpdate(ctx context.Context, in *PatchUpdateRequest, opts ...grpc.CallOption) (*Advent, error)
	Delete(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error)
}

type adventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdventServiceClient(cc grpc.ClientConnInterface) AdventServiceClient {
	return &adventServiceClient{cc}
}

func (c *adventServiceClient) Create(ctx context.Context, in *CreateAdventRequest, opts ...grpc.CallOption) (*Advent, error) {
	out := new(Advent)
	err := c.cc.Invoke(ctx, "/storage_service.AdventService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventServiceClient) Get(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*GetAdvent, error) {
	out := new(GetAdvent)
	err := c.cc.Invoke(ctx, "/storage_service.AdventService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventServiceClient) GetList(ctx context.Context, in *GetListAdventRequest, opts ...grpc.CallOption) (*GetAdventsListResponse, error) {
	out := new(GetAdventsListResponse)
	err := c.cc.Invoke(ctx, "/storage_service.AdventService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventServiceClient) Update(ctx context.Context, in *UpdateAdventRequest, opts ...grpc.CallOption) (*Advent, error) {
	out := new(Advent)
	err := c.cc.Invoke(ctx, "/storage_service.AdventService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventServiceClient) PatchUpdate(ctx context.Context, in *PatchUpdateRequest, opts ...grpc.CallOption) (*Advent, error) {
	out := new(Advent)
	err := c.cc.Invoke(ctx, "/storage_service.AdventService/PatchUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adventServiceClient) Delete(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/storage_service.AdventService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdventServiceServer is the server API for AdventService service.
// All implementations must embed UnimplementedAdventServiceServer
// for forward compatibility
type AdventServiceServer interface {
	Create(context.Context, *CreateAdventRequest) (*Advent, error)
	Get(context.Context, *PrimaryKey) (*GetAdvent, error)
	GetList(context.Context, *GetListAdventRequest) (*GetAdventsListResponse, error)
	Update(context.Context, *UpdateAdventRequest) (*Advent, error)
	PatchUpdate(context.Context, *PatchUpdateRequest) (*Advent, error)
	Delete(context.Context, *PrimaryKey) (*empty.Empty, error)
	mustEmbedUnimplementedAdventServiceServer()
}

// UnimplementedAdventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdventServiceServer struct {
}

func (UnimplementedAdventServiceServer) Create(context.Context, *CreateAdventRequest) (*Advent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedAdventServiceServer) Get(context.Context, *PrimaryKey) (*GetAdvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedAdventServiceServer) GetList(context.Context, *GetListAdventRequest) (*GetAdventsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedAdventServiceServer) Update(context.Context, *UpdateAdventRequest) (*Advent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedAdventServiceServer) PatchUpdate(context.Context, *PatchUpdateRequest) (*Advent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchUpdate not implemented")
}
func (UnimplementedAdventServiceServer) Delete(context.Context, *PrimaryKey) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAdventServiceServer) mustEmbedUnimplementedAdventServiceServer() {}

// UnsafeAdventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdventServiceServer will
// result in compilation errors.
type UnsafeAdventServiceServer interface {
	mustEmbedUnimplementedAdventServiceServer()
}

func RegisterAdventServiceServer(s grpc.ServiceRegistrar, srv AdventServiceServer) {
	s.RegisterService(&AdventService_ServiceDesc, srv)
}

func _AdventService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAdventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_service.AdventService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).Create(ctx, req.(*CreateAdventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_service.AdventService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).Get(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListAdventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_service.AdventService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).GetList(ctx, req.(*GetListAdventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAdventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_service.AdventService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).Update(ctx, req.(*UpdateAdventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventService_PatchUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).PatchUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_service.AdventService/PatchUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).PatchUpdate(ctx, req.(*PatchUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdventService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdventServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage_service.AdventService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdventServiceServer).Delete(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// AdventService_ServiceDesc is the grpc.ServiceDesc for AdventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage_service.AdventService",
	HandlerType: (*AdventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AdventService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AdventService_Get_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _AdventService_GetList_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AdventService_Update_Handler,
		},
		{
			MethodName: "PatchUpdate",
			Handler:    _AdventService_PatchUpdate_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AdventService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "advent_service.proto",
}
