// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: advent.proto

package organization_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Advent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BranchId   string `protobuf:"bytes,2,opt,name=branchId,proto3" json:"branchId,omitempty"`
	SupplierId string `protobuf:"bytes,3,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	Status     string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AdventId   string `protobuf:"bytes,5,opt,name=AdventId,proto3" json:"AdventId,omitempty"`
	CreatedAt  string `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *Advent) Reset() {
	*x = Advent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Advent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advent) ProtoMessage() {}

func (x *Advent) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advent.ProtoReflect.Descriptor instead.
func (*Advent) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{0}
}

func (x *Advent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Advent) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *Advent) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *Advent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Advent) GetAdventId() string {
	if x != nil {
		return x.AdventId
	}
	return ""
}

func (x *Advent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateAdventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BranchId   string `protobuf:"bytes,1,opt,name=branchId,proto3" json:"branchId,omitempty"`
	SupplierId string `protobuf:"bytes,2,opt,name=supplierId,proto3" json:"supplierId,omitempty"`
	Status     string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	AdventId   string `protobuf:"bytes,4,opt,name=AdventId,proto3" json:"AdventId,omitempty"`
	CreatedAt  string `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *CreateAdventRequest) Reset() {
	*x = CreateAdventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdventRequest) ProtoMessage() {}

func (x *CreateAdventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdventRequest.ProtoReflect.Descriptor instead.
func (*CreateAdventRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdventRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *CreateAdventRequest) GetSupplierId() string {
	if x != nil {
		return x.SupplierId
	}
	return ""
}

func (x *CreateAdventRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAdventRequest) GetAdventId() string {
	if x != nil {
		return x.AdventId
	}
	return ""
}

func (x *CreateAdventRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type GetListAdventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Branch   string `protobuf:"bytes,1,opt,name=branch,proto3" json:"branch,omitempty"`
	AdventId string `protobuf:"bytes,2,opt,name=adventId,proto3" json:"adventId,omitempty"`
}

func (x *GetListAdventRequest) Reset() {
	*x = GetListAdventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListAdventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListAdventRequest) ProtoMessage() {}

func (x *GetListAdventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListAdventRequest.ProtoReflect.Descriptor instead.
func (*GetListAdventRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{2}
}

func (x *GetListAdventRequest) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GetListAdventRequest) GetAdventId() string {
	if x != nil {
		return x.AdventId
	}
	return ""
}

type GetAdventsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Advents []*Advent `protobuf:"bytes,1,rep,name=advents,proto3" json:"advents,omitempty"`
	Count   int32     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetAdventsListResponse) Reset() {
	*x = GetAdventsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdventsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdventsListResponse) ProtoMessage() {}

func (x *GetAdventsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdventsListResponse.ProtoReflect.Descriptor instead.
func (*GetAdventsListResponse) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdventsListResponse) GetAdvents() []*Advent {
	if x != nil {
		return x.Advents
	}
	return nil
}

func (x *GetAdventsListResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateAdventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Advent *Advent `protobuf:"bytes,1,opt,name=advent,proto3" json:"advent,omitempty"`
}

func (x *UpdateAdventRequest) Reset() {
	*x = UpdateAdventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_advent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdventRequest) ProtoMessage() {}

func (x *UpdateAdventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_advent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdventRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdventRequest) Descriptor() ([]byte, []int) {
	return file_advent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateAdventRequest) GetAdvent() *Advent {
	if x != nil {
		return x.Advent
	}
	return nil
}

var File_advent_proto protoreflect.FileDescriptor

var file_advent_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14,
	0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0xa6, 0x01, 0x0a, 0x06, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73,
	0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa3, 0x01,
	0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x62, 0x72, 0x61, 0x6e, 0x63, 0x68, 0x49,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x64, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x41, 0x64, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x4a, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x72, 0x61, 0x6e, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x72, 0x61,
	0x6e, 0x63, 0x68, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22,
	0x66, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x61, 0x64, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x67,
	0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x4b, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34,
	0x0a, 0x06, 0x61, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x61, 0x64,
	0x76, 0x65, 0x6e, 0x74, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_advent_proto_rawDescOnce sync.Once
	file_advent_proto_rawDescData = file_advent_proto_rawDesc
)

func file_advent_proto_rawDescGZIP() []byte {
	file_advent_proto_rawDescOnce.Do(func() {
		file_advent_proto_rawDescData = protoimpl.X.CompressGZIP(file_advent_proto_rawDescData)
	})
	return file_advent_proto_rawDescData
}

var file_advent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_advent_proto_goTypes = []interface{}{
	(*Advent)(nil),                 // 0: organization_service.Advent
	(*CreateAdventRequest)(nil),    // 1: organization_service.CreateAdventRequest
	(*GetListAdventRequest)(nil),   // 2: organization_service.GetListAdventRequest
	(*GetAdventsListResponse)(nil), // 3: organization_service.GetAdventsListResponse
	(*UpdateAdventRequest)(nil),    // 4: organization_service.UpdateAdventRequest
}
var file_advent_proto_depIdxs = []int32{
	0, // 0: organization_service.GetAdventsListResponse.advents:type_name -> organization_service.Advent
	0, // 1: organization_service.UpdateAdventRequest.advent:type_name -> organization_service.Advent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_advent_proto_init() }
func file_advent_proto_init() {
	if File_advent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_advent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Advent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListAdventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdventsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_advent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAdventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_advent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_advent_proto_goTypes,
		DependencyIndexes: file_advent_proto_depIdxs,
		MessageInfos:      file_advent_proto_msgTypes,
	}.Build()
	File_advent_proto = out.File
	file_advent_proto_rawDesc = nil
	file_advent_proto_goTypes = nil
	file_advent_proto_depIdxs = nil
}
